### PR TITLE
Added the ability to suspend and unsuspend the hotkeys

### PR DESCRIPTION
**Pull request by PandaHajs**

### CODE REVIEW

**Review by jakubmanczak — CHANGES_REQUESTED** [review]
It seems like after enabling support for suspending hotkeys writing ẞ (Left Alt + Shift + S) suspends them by default. Could be a default suspension hotkey, could be something else. One thing for sure is it's gotta be fixed. ;0
image

**Comment by PandaHajs** [comment]
Understood, will do!

**Comment by jakubmanczak** [comment]
Documenting stuff more broadly than the title would be nice as well, but I'm not going to push it. ;)

**Comment by PandaHajs** [comment]
Replacing the part of the code that suspends it to the begging fixed it, so it should work now. I've also added the hotkey to  README.md

**Review by jakubmanczak — APPROVED** [review]
Seems to have worked! Will merge.

**Pull request merged**
